### ISSUE TITLE
Add back in compare operations for dynamic_bit_vector

### ISSUE THREAD

**Issue by rdaly525** [dillonhuff/bsim#2]
I need this before I am able to give you the linebuffermem. At the bare minimum operator< and operator==

**Comment by dillonhuff** [comment]
Do you want the default > and < operators to implement signed or unsigned comparison on bit vectors? For example should

```cpp

dynamic_bit_vector a(3, "100");
dynamic_bit_vector b(3, "001");

return  a > b;
```

Return true or false?

Or do you want to have ```dynamic_signed_int``` and ```dynamic_unsigned_int``` wrapper classes like in the static version?

**Comment by rdaly525** [comment]
Lets just assume that it is unsigned. I really only need '<' to be able to store these as keys in a map.

**Comment by dillonhuff** [comment]
Just pushed a new version with '<' and '>'. LMK if it was what you need.
