### ISSUE TITLE
Broken constructor and get_type in dynamic_bit_vector

### ISSUE THREAD

**Issue by rdaly525** [dillonhuff/bsim#3]
specifically the constructor:
dynamic_bit_vector(const int N_, const int val);

get_type() also does not work as far as I can tell.

**Comment by dillonhuff** [comment]
The constructor should be fixed now. I have added a real implementation and a unit test in test/dynamic_bitvector_tests.cpp.

What is get_type()? The library does not have any functions or methods by that name.

If you mean to_type() I believe that is now fixed.
